import type { MetadataRoute } from 'next';
import { SEO } from '@/lib/seo';

/**
 * robots.txt — auto-generated by Next.js App Router.
 * Accessible at: https://nehalnadaf.me/robots.txt
 *
 * Strategy:
 *   - Wildcard rule allows all standard crawlers, blocks Next.js internals
 *   - Each AI/LLM crawler gets an EXPLICIT allow block.
 *     Without explicit rules, some AI crawlers default to blocked or use
 *     only the training data cutoff rather than live crawling.
 *
 * AI crawlers covered:
 *   GPTBot, OAI-SearchBot, ChatGPT-User (OpenAI)
 *   ClaudeBot, Claude-Web                (Anthropic)
 *   PerplexityBot                         (Perplexity)
 *   Google-Extended                       (Gemini training)
 *   Applebot-Extended                     (Apple AI)
 *   YouBot                                (You.com)
 *   Diffbot                               (enterprise AI graph)
 *   Bytespider                            (TikTok/ByteDance AI)
 *   anthropic-ai                          (Anthropic internal)
 */
export default function robots(): MetadataRoute.Robots {
  const disallowCommon = [
    '/admin/',  // Admin routes — protected / private
    '/_next/',  // Next.js internal assets (JS chunks, etc.)
    '/api/',    // API routes — not crawlable pages
    '/sw.js',   // Service worker — not an HTML page
  ];

  return {
    rules: [
      // ── Standard crawlers (Google, Bing, etc.) ──────────────────────────────
      {
        userAgent: '*',
        allow: '/',
        disallow: disallowCommon,
      },

      // ── OpenAI ──────────────────────────────────────────────────────────────
      // GPTBot: used to train GPT models and power ChatGPT browsing
      {
        userAgent: 'GPTBot',
        allow: '/',
        disallow: disallowCommon,
      },
      // OAI-SearchBot: OpenAI's SearchGPT / web search product
      {
        userAgent: 'OAI-SearchBot',
        allow: '/',
        disallow: disallowCommon,
      },
      // ChatGPT-User: ChatGPT real-time browsing (plugin / Browse with Bing)
      {
        userAgent: 'ChatGPT-User',
        allow: '/',
        disallow: disallowCommon,
      },

      // ── Anthropic ───────────────────────────────────────────────────────────
      // ClaudeBot: Anthropic's primary training and Claude.ai browsing crawler
      {
        userAgent: 'ClaudeBot',
        allow: '/',
        disallow: disallowCommon,
      },
      // Claude-Web: Anthropic real-time web access (Claude.ai)
      {
        userAgent: 'Claude-Web',
        allow: '/',
        disallow: disallowCommon,
      },
      // anthropic-ai: internal Anthropic research crawler
      {
        userAgent: 'anthropic-ai',
        allow: '/',
        disallow: disallowCommon,
      },

      // ── Perplexity ──────────────────────────────────────────────────────────
      {
        userAgent: 'PerplexityBot',
        allow: '/',
        disallow: disallowCommon,
      },

      // ── Google AI ───────────────────────────────────────────────────────────
      // Google-Extended: controls whether content is used to train Gemini
      {
        userAgent: 'Google-Extended',
        allow: '/',
        disallow: disallowCommon,
      },

      // ── Apple ───────────────────────────────────────────────────────────────
      {
        userAgent: 'Applebot-Extended',
        allow: '/',
        disallow: disallowCommon,
      },

      // ── You.com ─────────────────────────────────────────────────────────────
      {
        userAgent: 'YouBot',
        allow: '/',
        disallow: disallowCommon,
      },

      // ── Diffbot ─────────────────────────────────────────────────────────────
      {
        userAgent: 'Diffbot',
        allow: '/',
        disallow: disallowCommon,
      },

      // ── ByteDance / TikTok ──────────────────────────────────────────────────
      {
        userAgent: 'Bytespider',
        allow: '/',
        disallow: disallowCommon,
      },
    ],
    sitemap: `${SEO.baseUrl}/sitemap.xml`,
    // NOTE: `host` is a Yandex-only directive not part of the robots.txt standard.
    // Removed to keep the output spec-compliant.
  };
}
