import type { MetadataRoute } from 'next';
import { SEO } from '@/lib/seo';

/**
 * robots.txt — auto-generated by Next.js App Router.
 * Accessible at: https://nehalnadaf.com/robots.txt
 *
 * Strategy: allow all crawlers, disallow Next.js internal routes,
 * point to sitemap for efficient crawl budget use.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/_next/',
          '/api/',
        ],
      },
    ],
    sitemap: `${SEO.baseUrl}/sitemap.xml`,
    host: SEO.baseUrl,
  };
}
