import type { MetadataRoute } from 'next';
import { SEO } from '@/lib/seo';

/**
 * Dynamic sitemap.xml — auto-generated by Next.js App Router.
 * Accessible at: https://nehalnadaf.com/sitemap.xml
 *
 * Priorities follow the SEO guide:
 * - Homepage: 1.0 (highest)
 * - Key portfolio pages: 0.9
 * - Secondary pages: 0.8
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = SEO.baseUrl;
  const now = new Date();

  return [
    {
      url: base,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 1.0,
    },
    {
      url: `${base}/projects`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${base}/videos`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${base}/influencers`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  ];
}
