import type { MetadataRoute } from 'next';
import { SEO } from '@/lib/seo';

/**
 * Dynamic sitemap.xml — auto-generated by Next.js App Router.
 * Accessible at: https://nehalnadaf.me/sitemap.xml
 *
 * Priorities follow the SEO guide:
 * - Homepage: 1.0 (highest)
 * - Key portfolio pages: 0.9
 * - Secondary pages: 0.8
 *
 * lastModified uses accurate static dates per page — NOT new Date() —
 * so Googlebot only re-crawls pages whose content has actually changed.
 * Update the date for a page when you meaningfully update its content.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = SEO.baseUrl;

  return [
    {
      url: base,
      lastModified: new Date('2026-07-27'),
      changeFrequency: 'monthly',
      priority: 1.0,
      alternates: {
        languages: {
          'en-IN': base,
          'x-default': base,
        },
      },
    },
    {
      url: `${base}/projects`,
      lastModified: new Date('2026-07-27'),
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: {
        languages: {
          'en-IN': `${base}/projects`,
          'x-default': `${base}/projects`,
        },
      },
    },
    {
      url: `${base}/videos`,
      lastModified: new Date('2026-07-27'),
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: {
        languages: {
          'en-IN': `${base}/videos`,
          'x-default': `${base}/videos`,
        },
      },
    },
    {
      url: `${base}/influencers`,
      lastModified: new Date('2026-07-27'),
      changeFrequency: 'monthly',
      priority: 0.9,
      alternates: {
        languages: {
          'en-IN': `${base}/influencers`,
          'x-default': `${base}/influencers`,
        },
      },
    },
  ];
}
