import type { MetadataRoute } from 'next';
import { SEO } from '@/lib/seo';

/**
 * Dynamic sitemap.xml — auto-generated by Next.js App Router.
 * Accessible at: https://nehalnadaf.me/sitemap.xml
 *
 * BUILD_DATE reflects the actual deploy time so Googlebot sees a fresh
 * lastModified on every deploy rather than a frozen static date.
 *
 * To add a new route: append an entry to the ROUTES array below.
 * The alternates/languages boilerplate is generated automatically.
 *
 * Priority reference:
 *   1.0   Homepage
 *   0.90  Core portfolio pages (projects, videos, influencers)
 *   0.85  Contact + service pages (high conversion intent)
 *   0.80  About page
 */

const BUILD_DATE = new Date();

interface RouteConfig {
  path: string;
  priority: number;
  changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency'];
}

const ROUTES: RouteConfig[] = [
  // ── Core pages ────────────────────────────────────────────────────────────
  { path: '/',                                  priority: 1.00, changeFrequency: 'monthly' },
  { path: '/about',                             priority: 0.80, changeFrequency: 'monthly' },
  { path: '/contact',                           priority: 0.85, changeFrequency: 'monthly' },
  // ── Portfolio pages ───────────────────────────────────────────────────────
  { path: '/projects',                          priority: 0.90, changeFrequency: 'weekly'  },
  { path: '/videos',                            priority: 0.90, changeFrequency: 'weekly'  },
  { path: '/influencers',                       priority: 0.90, changeFrequency: 'monthly' },
  // ── Service pages ─────────────────────────────────────────────────────────
  { path: '/services/web-development',          priority: 0.85, changeFrequency: 'monthly' },
  { path: '/services/ui-ux-design',             priority: 0.85, changeFrequency: 'monthly' },
  { path: '/services/video-editing',            priority: 0.85, changeFrequency: 'monthly' },
  { path: '/services/social-media-marketing',   priority: 0.85, changeFrequency: 'monthly' },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const base = SEO.baseUrl;

  return ROUTES.map((route) => ({
    url: `${base}${route.path}`,
    lastModified: BUILD_DATE,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
    alternates: {
      languages: {
        'en-IN': `${base}${route.path}`,
        'x-default': `${base}${route.path}`,
      },
    },
  }));
}
